wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
architecture:
  desc: null
  value: ResnetDepthUnet
dataset:
  desc: null
  value: WayFAST
epochs:
  desc: null
  value: 50
_wandb:
  desc: null
  value:
    python_version: 3.10.1
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1715545529.0
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.10.1
      5: 0.16.6
      6: 4.36.2
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
